### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by gachiemchiep** [IRVLUTD/isaac_sim_grasping#1]
Some of the links on README.md are broken.
For example:

* Google Scanned Objects and YCB objects .usd files [here](https://utdallas.box.com/s/bfc81l7ypaaa3s0niaz1miylbdgul7b7)
* Filtered GraspIt Grasps Dataset [here](https://utdallas.box.com/shared/static/cvrr97gylkonno7hokmyn80k36u9ts7f.zip)
* Transferred Grasps Dataset [here](https://utdallas.box.com/shared/static/vtanakqjqqet61s3doxu9196vg6tjxs9.zip)

Would you mind add the links again. 

Thank you very much.

**Comment by kninad** [comment]
Thanks for noticing this! I updated the README to remove these links as these folders can already be accessed with [this link](https://utdallas.box.com/v/multi-gripper-grasp-data) to the parent dataset folder mentioned in the README.
