### ISSUE TITLE
AttributeError: 'World' object has no attribute 'dc_interface'

### ISSUE THREAD

**Issue by chenjiayi-zxx** [IRVLUTD/isaac_sim_grasping#8]
When calling the post_reset method, an attempt is made to access the dc_interface attribute of the World object, but it raises the following error:
AttributeError: 'World' object has no attribute 'dc_interface'
After reviewing the documentation and codebase, I could not find any reference to dc_interface being a part of the World object. It's unclear whether this is a missing feature, an undocumented change, or a required initialization step.
Set up the environment:
Isaac Sim version: 4.1.0
Python version: 3.10
Operating System: Ubuntu 20.04

**Comment by FelipeCasas** [comment]
Hello, thanks for reaching out. This kind of error happens regularly when switching to new Isaac Sim versions. I would recommend using the 2023.0.1 or 2023.1.1 versions which were used to create the simulation. Let us know if the error persists after doing so. 

Kind Regards, 
Luis Felipe Casas

**Comment by longshot-pting** [comment]
> When calling the post_reset method, an attempt is made to access the dc_interface attribute of the World object, but it raises the following error: AttributeError: 'World' object has no attribute 'dc_interface' After reviewing the documentation and codebase, I could not find any reference to dc_interface being a part of the World object. It's unclear whether this is a missing feature, an undocumented change, or a required initialization step. Set up the environment: Isaac Sim version: 4.1.0 Python version: 3.10 Operating System: Ubuntu 20.04

hi! how did you solve this question? By changing version?

**Comment by chenjiayi-zxx** [comment]
@longshot-pting 
Yes, I solved this problem by changing to the 2023 version

**Comment by longshot-pting** [comment]
> @longshot-pting Yes, I solved this problem by changing to the 2023 version

thanks for replying, I ask my leader who had successfully solved this problem in version 24.2. You can use ''from omni.isaac.dynamic_control import _dynamic_control''  and ''dc = _dynamic_control.acquire_dynamic_control_interface()'' to get dc for new version change this attribute in dynamic_control.

**Comment by FelipeCasas** [comment]
The repo has been updated to be compatible with Isaac Sim 4.2.0. Please let us know if there are any other issues when using the newer Isaac Sim versions.
