### ISSUE TITLE
How about synthecizing grasping poses for cluttered scenes?

### ISSUE THREAD

**Issue by albertcity** [IRVLUTD/isaac_sim_grasping#9]
Dear authors,
Are there any plans to develop a synthesis pipeline for cluttered scenes? (which include multiple objects and we need to sample a collision-free grasp pose. Such data may possiblly be obtained by utilizing motion-planning tools such as Curobo).

**Comment by FelipeCasas** [comment]
Hello, thank you for reaching out!

Such features would definitely be a nice addition to our repository. We are currently deciding the direction to take for the near future. We recommend staying tuned on our research by watching the repository and following our Lab github account @IRVLUTD. You can also follow our lab on X with the same tag"@IRVLUTD" or visit our website https://labs.utdallas.edu/irvl/ to learn more about our current projects. 

Kind Regards
